package access

import (
	"context"
	"fmt"

	"github.com/dionisius77/dorm/errkind"
	dormerrors "github.com/dionisius77/dorm/errors"
	"github.com/dionisius77/dorm/schema"
)

// Operation identifies the access engine operation being evaluated.
type Operation string

const (
	OpQuery  Operation = "query"
	OpInsert Operation = "insert"
	OpUpdate Operation = "update"
	OpDelete Operation = "delete"
)

// Engine applies access policies and injects scoped values.
type Engine struct{}

// NewEngine returns a default access engine.
func NewEngine() Engine { return Engine{} }

// Predicate represents a SQL predicate generated by access policy evaluation.
type Predicate struct {
	SQL  string
	Args []any
}

// FieldValue represents a field assignment generated by access policy evaluation.
type FieldValue struct {
	Field string
	Value any
}

// MissingContextError reports a required access context value that was absent.
type MissingContextError struct {
	Base      *dormerrors.AccessError
	Operation Operation
	Field     string
	Reason    string
}

func (e *MissingContextError) Is(target error) bool {
	if e == nil {
		return false
	}
	if target == nil {
		return false
	}
	switch target {
	case dormerrors.ErrInvalidContext, dormerrors.ErrMissingCompany, dormerrors.ErrPolicyDenied, dormerrors.ErrAccessViolation:
		return true
	}
	if t, ok := target.(*dormerrors.Error); ok {
		switch t.Kind {
		case dormerrors.KindInvalidContext, dormerrors.KindMissingCompany, dormerrors.KindPolicyDenied, dormerrors.KindAccessViolation:
			return true
		}
	}
	return dormerrors.Is(e.Base, target)
}

func (e *MissingContextError) Error() string {
	if e == nil {
		return "access: missing context"
	}
	if e.Base != nil {
		return e.Base.Error()
	}
	if e.Reason != "" {
		return fmt.Sprintf("access: %s requires %s: %s", e.Operation, e.Field, e.Reason)
	}
	return fmt.Sprintf("access: %s requires %s", e.Operation, e.Field)
}

func (e *MissingContextError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.Base
}

func newMissingContextError(op Operation, field, reason string) error {
	kind := dormerrors.KindInvalidContext
	if field == "CompanyID" {
		kind = dormerrors.KindMissingCompany
	}
	base := &dormerrors.AccessError{
		Base:      &dormerrors.Error{Kind: kind, Message: fmt.Sprintf("access: %s requires %s: %s", op, field, reason)},
		Operation: string(op),
		Policy:    "default",
		Field:     field,
		Reason:    reason,
	}
	return &MissingContextError{Base: base, Operation: op, Field: field, Reason: reason}
}

func (Engine) Apply(ctx context.Context, table *schema.Table, op Operation, values map[string]any) ([]Predicate, []FieldValue, error) {
	ac, _ := FromContext(ctx)
	policy := ac.Policy.Normalize()
	var predicates []Predicate
	var writes []FieldValue
	if table == nil {
		return nil, nil, errkind.New(errkind.KindConfiguration, "access: nil table")
	}

	if err := validateContextForOperation(ac, table, op, policy); err != nil {
		return nil, nil, err
	}

	for _, col := range table.Columns {
		if policy.AllowsScope(col.Scope) {
			switch col.Scope {
			case schema.ScopeCompany:
				if op == OpQuery || op == OpDelete {
					predicates = append(predicates, Predicate{SQL: col.Name + " = ?", Args: []any{ac.CompanyID}})
				}
				if op == OpInsert {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.CompanyID})
				}
			case schema.ScopeTenant:
				if op == OpQuery || op == OpDelete {
					predicates = append(predicates, Predicate{SQL: col.Name + " = ?", Args: []any{ac.TenantID}})
				}
				if op == OpInsert {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.TenantID})
				}
			case schema.ScopeOrganization:
				if op == OpQuery || op == OpDelete {
					predicates = append(predicates, Predicate{SQL: col.Name + " = ?", Args: []any{ac.OrganizationID}})
				}
				if op == OpInsert {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.OrganizationID})
				}
			case schema.ScopeWorkspace:
				if op == OpQuery || op == OpDelete {
					predicates = append(predicates, Predicate{SQL: col.Name + " = ?", Args: []any{ac.WorkspaceID}})
				}
				if op == OpInsert {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.WorkspaceID})
				}
			case schema.ScopeWarehouse:
				if op == OpQuery || op == OpDelete {
					predicates = append(predicates, Predicate{SQL: col.Name + " = ?", Args: []any{ac.WarehouseID}})
				}
				if op == OpInsert {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.WarehouseID})
				}
			case schema.ScopeUser:
				if op == OpQuery || op == OpDelete {
					predicates = append(predicates, Predicate{SQL: col.Name + " = ?", Args: []any{ac.UserID}})
				}
				if op == OpInsert {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.UserID})
				}
			}
		}

		if !policy.EnforcesAudit() {
			continue
		}
		if op == OpInsert {
			switch {
			case col.CreatedBy:
				if ac.UserID != nil {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.UserID})
				}
			case col.UpdatedBy:
				if ac.UserID != nil {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.UserID})
				}
			case col.DeletedBy:
				if ac.UserID != nil {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.UserID})
				}
			}
		}
		if op == OpUpdate {
			switch {
			case col.UpdatedBy:
				if ac.UserID != nil {
					writes = append(writes, FieldValue{Field: col.Name, Value: ac.UserID})
				}
			}
		}
	}
	return predicates, writes, nil
}

func validateContextForOperation(ac Context, table *schema.Table, op Operation, policy Policy) error {
	if policy.IsSystem() {
		return nil
	}
	for _, col := range table.Columns {
		if policy.AllowsScope(col.Scope) {
			switch col.Scope {
			case schema.ScopeCompany:
				if ac.CompanyID == nil {
					return newMissingContextError(op, "CompanyID", "company-scoped model requires company context")
				}
			case schema.ScopeTenant:
				if ac.TenantID == nil {
					return newMissingContextError(op, "TenantID", "tenant-scoped model requires tenant context")
				}
			case schema.ScopeOrganization:
				if ac.OrganizationID == nil {
					return newMissingContextError(op, "OrganizationID", "organization-scoped model requires organization context")
				}
			case schema.ScopeWorkspace:
				if ac.WorkspaceID == nil {
					return newMissingContextError(op, "WorkspaceID", "workspace-scoped model requires workspace context")
				}
			case schema.ScopeWarehouse:
				if ac.WarehouseID == nil {
					return newMissingContextError(op, "WarehouseID", "warehouse-scoped model requires warehouse context")
				}
			case schema.ScopeUser:
				if ac.UserID == nil {
					return newMissingContextError(op, "UserID", "user-scoped model requires user context")
				}
			}
		}

		if !policy.EnforcesAudit() {
			continue
		}
		switch op {
		case OpInsert:
			switch {
			case col.CreatedBy, col.UpdatedBy, col.DeletedBy:
				if ac.UserID == nil {
					return newMissingContextError(op, "UserID", "audit fields require user context")
				}
			}
		case OpUpdate:
			if col.UpdatedBy && ac.UserID == nil {
				return newMissingContextError(op, "UserID", "updated_by requires user context")
			}
		case OpDelete:
			if col.DeletedBy && ac.UserID == nil {
				return newMissingContextError(op, "UserID", "deleted_by requires user context")
			}
		}
	}
	return nil
}
