package postgres

import (
	"fmt"
	"strconv"
	"strings"

	"dorm/dialect"
	"dorm/schema"
)

type Dialect struct{}

func New() Dialect { return Dialect{} }

func (Dialect) Name() string { return "postgres" }

func (Dialect) Capabilities() dialect.Capabilities {
	return dialect.Capabilities{
		UUID:               true,
		JSONB:              true,
		ARRAY:              true,
		ENUM:               true,
		GeneratedColumns:   true,
		MaterializedViews:  true,
		PartialIndexes:     true,
		ExpressionIndexes:  true,
		Gin:                true,
		Gist:               true,
		IdentityColumns:    true,
		CompositeKeys:      true,
		CompositeIndexes:   true,
		PreparedStatements: true,
	}
}

func (Dialect) QuoteIdent(in string) string {
	return `"` + strings.ReplaceAll(in, `"`, `""`) + `"`
}

func (Dialect) Placeholder(i int) string {
	return "$" + strconv.Itoa(i)
}

func (d Dialect) ColumnDefinition(col *schema.Column) (string, error) {
	if col == nil {
		return "", fmt.Errorf("postgres: nil column")
	}
	typ := d.renderType(col)
	var parts []string
	parts = append(parts, d.QuoteIdent(col.Name), typ)
	if col.Identity {
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
	}
	if !col.Nullable && !col.PrimaryKey {
		parts = append(parts, "NOT NULL")
	}
	if col.Default != "" {
		parts = append(parts, "DEFAULT "+col.Default)
	}
	if col.Generated != "" {
		parts = append(parts, "GENERATED ALWAYS AS ("+col.Generated+") STORED")
	}
	return strings.Join(parts, " "), nil
}

func (d Dialect) renderType(col *schema.Column) string {
	typ := strings.TrimSpace(col.Type.Name)
	if typ == "" {
		switch col.Type.Kind {
		case schema.TypeBool:
			return "boolean"
		case schema.TypeInt:
			return "bigint"
		case schema.TypeFloat:
			return "double precision"
		case schema.TypeString:
			return "text"
		case schema.TypeBytes:
			return "bytea"
		case schema.TypeTime:
			return "timestamptz"
		case schema.TypeUUID:
			return "uuid"
		case schema.TypeJSON:
			return "jsonb"
		case schema.TypeArray:
			if col.Type.ArrayOf != nil {
				return d.renderType(&schema.Column{Type: *col.Type.ArrayOf}) + "[]"
			}
			return "text[]"
		default:
			return "text"
		}
	}
	switch strings.ToLower(typ) {
	case "string":
		return "text"
	case "json":
		return "jsonb"
	case "bool", "boolean":
		return "boolean"
	case "int", "int2", "int4", "int8", "bigint", "smallint", "integer":
		return typ
	case "float", "float4", "float8", "double precision", "numeric", "decimal":
		return typ
	case "time", "timestamp", "timestamptz", "date":
		return "timestamptz"
	default:
		if col.Type.Kind == schema.TypeArray && !strings.HasSuffix(typ, "[]") {
			return typ + "[]"
		}
		return typ
	}
}

func (d Dialect) RenderOperation(op schema.Operation) (string, error) {
	switch op.Kind {
	case schema.OpCreateTable:
		return d.renderCreateTable(op)
	case schema.OpDropTable:
		return "DROP TABLE IF EXISTS " + d.QuoteIdent(op.Table) + " CASCADE;", nil
	case schema.OpAddColumn:
		return d.renderAddColumn(op)
	case schema.OpDropColumn:
		return "ALTER TABLE " + d.QuoteIdent(op.Table) + " DROP COLUMN IF EXISTS " + d.QuoteIdent(op.Column.Name) + ";", nil
	case schema.OpAlterColumn:
		return d.renderAlterColumn(op)
	case schema.OpCreateIndex:
		return d.renderCreateIndex(op)
	case schema.OpDropIndex:
		return "DROP INDEX IF EXISTS " + d.QuoteIdent(op.Index.Name) + ";", nil
	case schema.OpCreateConstraint:
		return d.renderCreateConstraint(op)
	case schema.OpDropConstraint:
		return "ALTER TABLE " + d.QuoteIdent(op.Table) + " DROP CONSTRAINT IF EXISTS " + d.QuoteIdent(op.Constraint.Name) + ";", nil
	default:
		return "", fmt.Errorf("postgres: unsupported operation %q", op.Kind)
	}
}

func (d Dialect) RenderMigration(diff *schema.Diff) ([]string, error) {
	if diff == nil {
		return nil, nil
	}
	out := make([]string, 0, len(diff.Operations))
	for _, op := range diff.Operations {
		sql, err := d.RenderOperation(op)
		if err != nil {
			return nil, err
		}
		out = append(out, sql)
	}
	return out, nil
}

func (d Dialect) renderCreateTable(op schema.Operation) (string, error) {
	table := op.Table
	if table == "" {
		return "", fmt.Errorf("postgres: create table missing table name")
	}
	if op.TableDef == nil {
		return "", fmt.Errorf("postgres: create table missing table definition")
	}
	var defs []string
	for _, col := range op.TableDef.Columns {
		def, err := d.ColumnDefinition(col)
		if err != nil {
			return "", err
		}
		defs = append(defs, def)
	}
	if len(defs) == 0 {
		return "", fmt.Errorf("postgres: create table requires columns")
	}
	if pk := tablePrimaryKeyColumns(op.TableDef); len(pk) > 0 {
		var quoted []string
		for _, col := range pk {
			quoted = append(quoted, d.QuoteIdent(col))
		}
		defs = append(defs, "PRIMARY KEY ("+strings.Join(quoted, ", ")+")")
	}
	sql := "CREATE TABLE IF NOT EXISTS " + d.QuoteIdent(table) + " (\n  " + strings.Join(defs, ",\n  ") + "\n);"
	return sql, nil
}

func (d Dialect) renderAddColumn(op schema.Operation) (string, error) {
	def, err := d.ColumnDefinition(op.Column)
	if err != nil {
		return "", err
	}
	return "ALTER TABLE " + d.QuoteIdent(op.Table) + " ADD COLUMN IF NOT EXISTS " + def + ";", nil
}

func (d Dialect) renderAlterColumn(op schema.Operation) (string, error) {
	if op.Column == nil || op.Previous == nil {
		return "", fmt.Errorf("postgres: alter column requires column metadata")
	}
	var stmts []string
	if op.Column.Type.Name != op.Previous.Type.Name || op.Column.Type.Kind != op.Previous.Type.Kind {
		stmts = append(stmts, "ALTER TABLE "+d.QuoteIdent(op.Table)+" ALTER COLUMN "+d.QuoteIdent(op.Column.Name)+" TYPE "+d.renderType(op.Column))
	}
	if op.Column.Nullable != op.Previous.Nullable {
		if op.Column.Nullable {
			stmts = append(stmts, "ALTER TABLE "+d.QuoteIdent(op.Table)+" ALTER COLUMN "+d.QuoteIdent(op.Column.Name)+" DROP NOT NULL")
		} else {
			stmts = append(stmts, "ALTER TABLE "+d.QuoteIdent(op.Table)+" ALTER COLUMN "+d.QuoteIdent(op.Column.Name)+" SET NOT NULL")
		}
	}
	if op.Column.Default != op.Previous.Default {
		if op.Column.Default == "" {
			stmts = append(stmts, "ALTER TABLE "+d.QuoteIdent(op.Table)+" ALTER COLUMN "+d.QuoteIdent(op.Column.Name)+" DROP DEFAULT")
		} else {
			stmts = append(stmts, "ALTER TABLE "+d.QuoteIdent(op.Table)+" ALTER COLUMN "+d.QuoteIdent(op.Column.Name)+" SET DEFAULT "+op.Column.Default)
		}
	}
	if len(stmts) == 0 {
		return "-- no-op", nil
	}
	return strings.Join(stmts, ";\n") + ";", nil
}

func (d Dialect) renderCreateIndex(op schema.Operation) (string, error) {
	if op.Index == nil {
		return "", fmt.Errorf("postgres: create index requires index")
	}
	var parts []string
	parts = append(parts, "CREATE")
	if op.Index.Unique {
		parts = append(parts, "UNIQUE")
	}
	parts = append(parts, "INDEX IF NOT EXISTS", d.QuoteIdent(op.Index.Name), "ON", d.QuoteIdent(op.Table))
	if op.Index.Method != "" {
		parts = append(parts, "USING", op.Index.Method)
	}
	if op.Index.Expression != "" {
		parts = append(parts, "("+op.Index.Expression+")")
	} else {
		var cols []string
		for _, c := range op.Index.Columns {
			cols = append(cols, d.QuoteIdent(c))
		}
		parts = append(parts, "("+strings.Join(cols, ", ")+")")
	}
	if op.Index.Where != "" {
		parts = append(parts, "WHERE", op.Index.Where)
	}
	return strings.Join(parts, " ") + ";", nil
}

func (d Dialect) renderCreateConstraint(op schema.Operation) (string, error) {
	if op.Constraint == nil {
		return "", fmt.Errorf("postgres: create constraint requires constraint")
	}
	switch op.Constraint.Kind {
	case schema.ConstraintPrimaryKey:
		var cols []string
		for _, c := range op.Constraint.Columns {
			cols = append(cols, d.QuoteIdent(c))
		}
		return "ALTER TABLE " + d.QuoteIdent(op.Table) + " ADD CONSTRAINT " + d.QuoteIdent(op.Constraint.Name) + " PRIMARY KEY (" + strings.Join(cols, ", ") + ");", nil
	case schema.ConstraintUnique:
		var cols []string
		for _, c := range op.Constraint.Columns {
			cols = append(cols, d.QuoteIdent(c))
		}
		return "ALTER TABLE " + d.QuoteIdent(op.Table) + " ADD CONSTRAINT " + d.QuoteIdent(op.Constraint.Name) + " UNIQUE (" + strings.Join(cols, ", ") + ");", nil
	case schema.ConstraintForeignKey:
		var cols []string
		for _, c := range op.Constraint.Columns {
			cols = append(cols, d.QuoteIdent(c))
		}
		var refCols []string
		for _, c := range op.Constraint.ReferencedColumns {
			refCols = append(refCols, d.QuoteIdent(c))
		}
		stmt := "ALTER TABLE " + d.QuoteIdent(op.Table) + " ADD CONSTRAINT " + d.QuoteIdent(op.Constraint.Name) +
			" FOREIGN KEY (" + strings.Join(cols, ", ") + ") REFERENCES " + d.QuoteIdent(op.Constraint.ReferencedTable) +
			" (" + strings.Join(refCols, ", ") + ")"
		if op.Constraint.OnDelete != "" {
			stmt += " ON DELETE " + op.Constraint.OnDelete
		}
		if op.Constraint.OnUpdate != "" {
			stmt += " ON UPDATE " + op.Constraint.OnUpdate
		}
		return stmt + ";", nil
	case schema.ConstraintCheck:
		return "ALTER TABLE " + d.QuoteIdent(op.Table) + " ADD CONSTRAINT " + d.QuoteIdent(op.Constraint.Name) + " CHECK (" + op.Constraint.Expression + ");", nil
	default:
		return "", fmt.Errorf("postgres: unsupported constraint kind %q", op.Constraint.Kind)
	}
}

func tablePrimaryKeyColumns(table *schema.Table) []string {
	if table == nil {
		return nil
	}
	var cols []string
	for _, col := range table.Columns {
		if col.PrimaryKey {
			cols = append(cols, col.Name)
		}
	}
	return cols
}

func (d Dialect) RenderSelect(table string, columns []string, where []string, orderBy []string, limit, offset *int) (string, error) {
	if table == "" {
		return "", fmt.Errorf("postgres: empty table")
	}
	if len(columns) == 0 {
		columns = []string{"*"}
	}
	var b strings.Builder
	b.WriteString("SELECT ")
	b.WriteString(strings.Join(columns, ", "))
	b.WriteString(" FROM ")
	b.WriteString(d.QuoteIdent(table))
	if len(where) > 0 {
		b.WriteString(" WHERE ")
		b.WriteString(strings.Join(where, " AND "))
	}
	if len(orderBy) > 0 {
		b.WriteString(" ORDER BY ")
		b.WriteString(strings.Join(orderBy, ", "))
	}
	if limit != nil {
		b.WriteString(" LIMIT ")
		b.WriteString(strconv.Itoa(*limit))
	}
	if offset != nil {
		b.WriteString(" OFFSET ")
		b.WriteString(strconv.Itoa(*offset))
	}
	return b.String(), nil
}

func (d Dialect) RenderInsert(table string, columns []string, returning []string) (string, error) {
	if table == "" {
		return "", fmt.Errorf("postgres: empty table")
	}
	if len(columns) == 0 {
		return "", fmt.Errorf("postgres: insert requires columns")
	}
	var quoted []string
	for _, c := range columns {
		quoted = append(quoted, d.QuoteIdent(c))
	}
	var placeholders []string
	for i := range columns {
		placeholders = append(placeholders, d.Placeholder(i+1))
	}
	sql := "INSERT INTO " + d.QuoteIdent(table) + " (" + strings.Join(quoted, ", ") + ") VALUES (" + strings.Join(placeholders, ", ") + ")"
	if len(returning) > 0 {
		sql += " RETURNING " + joinQuoted(returning, d.QuoteIdent)
	}
	return sql, nil
}

func (d Dialect) RenderUpdate(table string, set []string, where []string, returning []string) (string, error) {
	if table == "" {
		return "", fmt.Errorf("postgres: empty table")
	}
	if len(set) == 0 {
		return "", fmt.Errorf("postgres: update requires set clauses")
	}
	sql := "UPDATE " + d.QuoteIdent(table) + " SET " + strings.Join(set, ", ")
	if len(where) > 0 {
		sql += " WHERE " + strings.Join(where, " AND ")
	}
	if len(returning) > 0 {
		sql += " RETURNING " + joinQuoted(returning, d.QuoteIdent)
	}
	return sql, nil
}

func (d Dialect) RenderDelete(table string, where []string, returning []string) (string, error) {
	if table == "" {
		return "", fmt.Errorf("postgres: empty table")
	}
	sql := "DELETE FROM " + d.QuoteIdent(table)
	if len(where) > 0 {
		sql += " WHERE " + strings.Join(where, " AND ")
	}
	if len(returning) > 0 {
		sql += " RETURNING " + joinQuoted(returning, d.QuoteIdent)
	}
	return sql, nil
}

func joinQuoted(items []string, quote func(string) string) string {
	quoted := make([]string, 0, len(items))
	for _, item := range items {
		quoted = append(quoted, quote(item))
	}
	return strings.Join(quoted, ", ")
}
